### PR TITLE
improved article pagination - fixes issue #863

### PR DESCRIPTION
**Pull request by TheBrenny**
added the ability to removed or show drafts and/or archived articles to the article pagination

### CODE REVIEW

**Comment by CraigChilds94** [comment]
Thanks for taking the time to do this for us; it would've been great if you could've made this PR to `0.9-dev` as then I can merge it in straight away.

**Comment by daviddarnes** [comment]
@CraigChilds94 shouldn't be hard to `cherry-pick` it over :)

**Comment by TheBrenny** [comment]
Still wanting a PR onto 0.9-Dev?

**Comment by daviddarnes** [comment]
@thebrenny if you move '#863' out of the title of this pull request and put it in the content then it should reference the issue, although it'll do the same now that I've mentioned it too :laughing:.

**Pull request closed without merging**
