### PR TITLE
Bug fixes and a few changes

### LINKED ISSUE #1068: fields edit  bug
### Summary

When I edit fields in extends channel, it exported a warning：
pic

And I find the source code `routes/fields.php`:
```
Route::post('admin/extend/fields/edit/(:num)', function($id) {
		$input = Input::get(array('type', 'field', 'key', 'label', 'attributes', 'pagetype'));
		
		if(empty($input['key'])) {
			$input['key'] = $input['label'];
		}
		
		$input['key'] = slug($input['key'], '_');
		
		foreach($input as $key => &$value) {
			$value = eq($value);
		}
```
But, the fields add function works well, the code:
```
	Route::post('admin/extend/fields/add', function() {
		$input = Input::get(array('type', 'field', 'key', 'label', 'attributes', 'pagetype'));
		
		if(empty($input['key'])) {
			$input['key'] = $input['label'];
		}
		
		$input['key'] = slug($input['key'], '_');
		
		// an array of items that we shouldn't encode - they're no XSS threat
		$dont_encode = array('attributes');
		
		foreach($input as $key => &$value) {
			if(in_array($key, $dont_encode)) continue;
			$value = eq($value);
		}
```

So, we can see the different code, `$dont_encode = array('attributes');` and `if(in_array($key, $dont_encode)) continue;`
### Expected Behaviour

- Add the two line code as fileds add post function 

### Actual Behaviour

- A list of steps you actually encountered

### Context details (if applicable)

- Anchor version:master branch
- Server setup:php 5.6
- URL

### LINKED ISSUE #1086: HTML page field results in Uncaught Exception
### Summary
Adding a custom page HTML field (called _description_ in my case) and using it in a template, results in an Uncaught Exception:
```
Uncaught Exception

Class 'Markdown' not found

Origin

anchor\models\extend.php on line 49

Trace

#0 [internal function]: System\Error::shutdown()
#1 {main}
```

### Expected Behaviour
The page field should yield the entered HTML instead of an exception.

### Actual Behaviour
It yields the exception as described above.

- Anchor version: 0.12.1
- Server setup: XAMPP 5.6.20 (Apache 2.4.17, PHP 5.6.20)

### LINKED ISSUE #1096: Database connection details visible on connection error while installation
I just installed the current 0.12.1 version. Seems like I made a typo in the database connection details, which produces an exception.  
**First problem**: You are presented the (although nicely formatted) exception page which provides no way to just correct the error but assumes you know you can safely use the browser back button. Kinda bad usability.  
**Second, way worse problem**: The connection details are visible in the exception text, including a potentially correct password (say I just misspelled my server name).

bildschirmfoto 2016-06-02 um 16 05 30

### LINKED ISSUE #1097: Path to image dragged in to editor is incorrect
### Summary

When installing AnchorCMS in a sub directory (/blog) and dragging in an image in to the Markdown editor, the code entered is:

``

It appears that there is a slash missing.

### Expected Behaviour

``

### Actual Behaviour

``

### Context details (if applicable)

- Anchor version: 0.12.1
- Server setup: LAMP
- URL: private/testing

### PR DESCRIPTION
**Pull request by Gerrit0**
I did my best to format this to be easily reviewed... Sorry, it got really long. Mostly in chronological order. I also added a commit section as several commits included fixes for multiple issues. 

### Fix for #1089 (Incorrect timezone for Dhaka)
`DateTimeZone::listAbbreviations` returns an incorrect list of timezone offsets because of historical reasons, it can still be used, however, if the list is iterated over and each timezone is calculated based on the time the script was run. [Credit is due to Jonathan on SO](http://stackoverflow.com/questions/1727077/generating-a-drop-down-list-of-timezones-with-php/21211073#21211073)

### Commits
- 738336f28419d954c87ac4ac8aa31dc81d560dd9

### Changes proposed:

- Refactored `timezones()` function to display correct offsets.

---

### Fix for #1034 (Migration issue)

There is already a pull request for this, but I needed to fix it to run the master repo on my machine so I used [elenachoi's solution](https://github.com/anchorcms/anchor-cms/issues/1034#issuecomment-207893147). 

### Commits
- a1b8b4b3c261952f7c5da1d72415f7cbf2c03fb0 

### Changes proposed

- Rename class `Migration_insert_dashboard_page_meta_key ` to `Migration_insert_default_dashboard_meta_key`

---

### Fix for #1046 (Custom JS is being escaped)

The cause of this bug was bc202b52e08cd48c5cea0508c83bd40fb588a645, as everything was encoded when first fetched, nearly every input was encoded twice, and the JS was encoded. The fix was to remove this, and also check everywhere `Input::get()` was used to ensure that encoding wasn't missed (nowhere...).

### Commits

- 40cf83eefbb9d659e54fbe7b7a4d43e47e2af00b
- b761f244bfeb69f09199fa055a5ff6bfe6c886df

### Changes proposed
- Revert bc202b52e08cd48c5cea0508c83bd40fb588a645, which encoded all input
- Remove decoding of input when updating post as it is no longer needed. 

---

### Display article HTML rather than article markdown
`article_markdown` used to be used in themes instead of `article_html` to display the markdown, however, due to 8c3ef08d681b55da553b9f04a30085bd4a16d125, `article_markdown` no longer correctly displayed the HTML. Rather than reverting that change, which I believe is good as it makes the function return what it sounds like it should return, I changed the theme to use `article_html`. 

### Commits
- fed237ed457506d52d434e0153f84def0bab7cc7

### Changes proposed
- Use `article_html` instead of `article_markdown` when displaying articles. 

---

### Add previewing posts functionality
I noticed the route in the `anchor/routes/posts.php` file which attempted to create a page which would return the translated markdown for previewing posts. As this would not display the markdown in the context of the used theme, I refactored this to be a preview page using the current theme and currently saved HTML. 

### Commits
- 76f6d7431e03b0de11b82b533cbb20867e3f2d5c

### Changes proposed
- Create `Route::get('admin/posts/preview/(:num)'` to allow previewing the current post.
- Remove broken `Route::post('admin/posts/preview'`. 
- Add `preview` to the language files for a preview button next to the save button at the top of posts.
- Add optional `$force` parameter to `Anchor::functions` to allow the preview to work in an admin route.

---

### Fix #1097 (path in images dropped on post) / Refactor uploading files

Before this, all files were uploaded to `content/`, which could lead to thousands of files in a single directory. Now, new files are stored in `content/yyyy/mm/`. Also, if a file with the same name was uploaded more than once, it would overwrite the original. Apparently I'm [not the only one](http://forums.anchorcms.com/general/adding-pictures-filenames) to run into this problem. In the process of doing this, I also fixed #1097.

### Commits
- 3fbe5d0772e4575450f2e98e9b8cb66f95157db4
- 27aa9cfa7288163abed60688eda4ac165db59d23

### Changes proposed
- Upload new files to `content/yyyy/mm/` instead of `content/`. 
- Files with identical names should be transparently renamed, instead of replacing the original. 
- Fix path when dragging an image onto posts (#1097)
- Fix upload script, `Test.PNG` should be uploaded as `Test.png`, not `Test-PNG.png`

---

### Fix #1086 (HTML page field)
This was easy... The field simply used the `Markdown` class which isn't used by Anchor. Changing it to `Parsedown` fixed the issue. I also added input filtering for Text fields as the assumption for their use is outputting text rather than HTML. 

### Commits
- 27aa9cfa7288163abed60688eda4ac165db59d23

### Changes proposed
- Add output filtering for text fields
- Use `Parsedown` instead of `Markdown` class. 
- Change filename for files to support directories with yyyy/mm (also mentioned above)

---

### Fix #1096 (Database connection details visible...)
Simple fix, changing the catch statement to catch all `Exception`s rather than just `PDOException`s allowed all exceptions to be caught and the installer to be notified without an error page. 

### Commits
- 8240ebdb3a118bb06706f57dadf76956526ec150

### Changes proposed
- Fix validator bug where if the value was null, checks would always pass (ran into this while making the installer break) 
- Catch `Exception` rather than `PDOException` to avoid showing database info if the connection fails
- Add `Notify::Read` to all install views so that the installer can be notified about what went wrong. 

---

### Fix #1068 (fields edit bug)
If an image or file is uploaded as a custom field to a post, and the post is saved, it would produce an error as the script assumed that every input in `$input` was a string. 

### Commits
- 9942a8d442b3ca9cb2f05180c25c821537374582

### Changes proposed
- Use `array_walk_recursive` instead of foreach to run the values through `eq()`

---

### Fix updating site variables / Fix matching site variables in posts
Whenever updating a site variable, I would be notified that it was successfully updated, but it would fail to update. Also, most tags failed to be parsed as the regex did not accept underscores. 

### Commits
- 3141c83a962b5a7a9614947acabcb8867969edc2

### Changes proposed
- Change regex to allow alphanumeric characters and underscores, and also to only check tags within {{}} instead of {}
- Fix edit function to correctly check if the key used was valid.

### CODE REVIEW

**Comment by daviddarnes** [comment]
This is awesome @Gerrit0, thanks for submitting these fixes. However it's best practise to be making a single pull request for a single issue/fix. Breaking them down into their own pull requests mean it's easier to review them. We might be able to merge these this time around, what do you think @rwarasaurus?

**Comment by Gerrit0** [comment]
I can see why that is best practice! I'll follow that convention in the future. 

Let me know if I should close this and resubmit each fix individually.

**Comment by daviddarnes** [comment]
I'll go with whatever @rwarasaurus suggests, thanks for understanding.

**Comment by rwarasaurus** [comment]
@Gerrit0 yes please!

**Comment by TheBrenny** [comment]
@Gerrit0,

What happened to the fix for #1097? I'm very much in favour of your solution, and if you still have the code for it, send it back on through! :smile_cat:

**Comment by Gerrit0** [comment]
@TheBrenny, I never ended up resubmitting that as it required another change which took a week or two to get merged in, by which time I had forgotten it. I'll try and get that resubmitted today.

**Comment by Gerrit0** [comment]
@TheBrenny, just tried to get Anchor running locally again to make sure the changes I made didn't break anything. 

I ran into #1122, and don't really have the time right now to go hunting through to see what causes it. Feel free to grab the changed code from the commits above and make the change yourself, or once #1122 is fixed I can resubmit the changes.

**Pull request closed without merging**
