### PR TITLE
Auth control when going to route login if user is already logged in

### PR DESCRIPTION
**Pull request by teamcreed**
This pull request fix the issue https://github.com/anchorcms/anchor-cms/issues/933

It seems that the master branch is missing the authentication control in the admin/login route. This commit will fix the bug if you can merge it.

### CODE REVIEW

**Comment by TheBrenny** [comment]
I did a PR for this, however I pushed it to the 0.9-Dev branch. I feel like master is becoming more dormant because its so far behind in many many many fixes.

@daviddarnes, can we delete the contents of the current master and merge 0.9-Dev into master? Master is so far behind and really needs the catch up. Plus, master has all the bugs which are fixed in 0.9-Dev.

**Comment by teamcreed** [comment]
@TheBrenny. Of course 0.9-Dev is ahead of master, but they put the documentation for a reason and there are rules to follow. Also your commit is missing the "before => install" on the array so if they merge your PR that will create an issue instead of fix the problem. I also don't think that is necessary to delete the máster branch, this one is behind on commit but have some codes that 0.9-Dev doesn't like the array on the admin/login route.

**Comment by daviddarnes** [comment]
@TheBrenny sorry but I'm not the best person to ask about branches, you're better off asking @CraigChilds94 or @kieronwilson I'm afraid. They're more up to date with that stuff.

**Comment by CraigChilds94** [comment]
@TheBrenny @teamcreed  `master` is supposed to be for the current version of anchor; ie. the one which we think works and can release. THIS Fix was already made in the `0.9-dev` branch; so once that's been tested the `0.9-dev` branch will be merged into `master` does this make sense? 

The reason `master` has become dormant is because we've not had a chance to test stuff to merge it in.

**Pull request closed without merging**
