### PR TITLE
Allow single level replies to comments

### LINKED ISSUE #727: Allow "replies" in comments
Rather than having a pure list of comments on an article, it would be nice if you could reply to a particular comment and create threaded discussions. Another way to accomplish this would be to insert links, similar to GitHub or StackOverflow, when you reference another comment.

Just an idea for the big 1.0.

### PR DESCRIPTION
**Pull request by ghost**
This is a correction of #745, history has *not* been re-written this time around!

> **note**: i did have to re-push some editor based fuck ups...

Closes #727 

screenshot

### CODE REVIEW

**Comment by TimohStudios** [comment]
I love this idea! The only problem I can think of is the ease of use. Can you maybe make a little snippet with how you would use this? 
_Sorry, had troubel wit wurdz_

**Comment by dhazelett** [comment]
This was meant to be really basic, it does not have recursion. So this really is one level deep.

Clicking to reply button next to a post will set the hidden field in the form for the "reply-to".

If I had more time and wasn't working on a soon to be dead branch I would have went hard on this PR.

**Comment by TimohStudios** [comment]
I understand. I've had some time to get back the wurdz. What I meant to ask is; could you give an example as to how one would implement this in their theme?

**Comment by dhazelett** [comment]
Oh yeah, give me a little and I'll try to take the time after some morning scrum.

Devon Hazelett
http://www.motosport.com
Web Developer

**Comment by daviddarnes** [comment]
I like this addition but I think it would be better suited in a more filled out plugin, something that enhances the whole commenting aspect. Thoughts?

**Comment by dhazelett** [comment]
Yeah, have we nailed down the plugin docs yet? I haven't dabbled into the 'sails' yet.

Devon Hazelett
http://www.motosport.com
Web Developer

**Comment by daviddarnes** [comment]
@dhazelett touché! Plugins is still a bit of a hazy area, I'd have to check with @kieronwilson or @CraigChilds94 on the current status of them in the latest dev build.

I want to push plugins for many reasons, to let the community make their creations with the aid of Anchor but also to keep the main CMS lean. It's not that we don't want the contributions, far from it. We just want to keep the core the core and let others build upon it for their site projects.

**Comment by dhazelett** [comment]
I feel you brother, that's why I like stackphp, it's great. If we could up the abstraction for Anchor and have middleware plugins would be a sinch. 

But since we have to make sure theme devs remember to callout these 'hooks' in templates in the current design, it's a little hit and miss. Especially as themes age and more plugins come out. And then again it all depends on the  implementation. If there were, say, 5 callouts per template I think that would cover most. e.g. (pseudo code)

```php
# article.php

Sail::hook('article.start')

# article logic

Sail::hook('article.end')

Sail::hook('comments.start')

# comment stuff

Sails::hook('comment')

Sails:: hook('comments.end')

```

I guess this all depends on how or system actually works though. Hope we can find or soon, is love to make some of these PR's into plugins/'sails'!

Devon Hazelett
http://www.motosport.com
Web Developer

**Comment by CraigChilds94** [comment]
I think plugins is being considered for `1.0` but development is slow (due to our busy lives).

**Comment by daviddarnes** [comment]
@CraigChilds94 fair enough. Just trying to make decisions on what features should and shouldn't be in the core.

**Comment by dhazelett** [comment]
I totally feel you man! I've got a newborn now.


-------- Original Message --------

**Pull request closed without merging**
