### PR TITLE
Update articles.php

### PR DESCRIPTION
**Pull request by invot**
Added a related posts function as well as a way to get articles by category ID.

http://forums.anchorcms.com/help/how-to-show-randomly-related-posts

### CODE REVIEW

**Comment by TimohStudios** [comment]
Oww, I think a related posts in the core would be pretty cool.

**Comment by daviddarnes** [comment]
Does nobody else think this would be better suited as a plugin? Seems like strange functionality to be directly added to the core.

**Comment by CraigChilds94** [comment]
@daviddarnes  It's hard to say, it would be neat and wouldn't cause much bloat but also doesn't feel vanilla. So I don't know :(

**Comment by TimohStudios** [comment]
Wait, why was this merged into master? @CraigChilds94 this really confuses me...

**Comment by TheBrenny** [comment]
@CraigChilds94: @daviddarnes suggested that this is better suited as a plugin, and I fully agree with that.

So I'm with @TimohStudios on this one. I think we should set up plugins functionality first. And then look at altering this PR to have it as a plugin rather than a feature.

From there we can also implement plugins into the core if it feels right, right?

**Comment by TimohStudios** [comment]
I think the addition is fine, I was just confused why it's merged into master instead 0f 0.9-dev

**Comment by TheBrenny** [comment]
Lol whoops, I forgot a double line break. My bad.

But I think @CraigChilds94 is cleaning everything up in preparation for a big 1.0.0? :3

**Comment by CraigChilds94** [comment]
Oh I merged this one in because I thought it wouldn't hurt. And I couldn't be bothered to faff with branches on this one. So merged into `master` then merged `master` into `0.9-dev`.

`1.0` is being handled by @rwarasaurus . I'm just trying to get another stable version of the current build up. So `0.9 -> 0.10`

**Pull request merged**
