### PR TITLE
Allow access to the admin asset folder

### PR DESCRIPTION
**Pull request by tijme**
It seems like my pull request #1248 broke access to the assets folder, as reported in issue #1249. The only access needed in the `/anchor` folder is for the assets, so I added a `.htaccess` file which allows all access to the assets folder. This seems like a clean fix to me.

To be sure everything works as it should I tested it just now on my local machine.

### Fix/Feature for #1249

The `Allow from all` in the assets folder allows all access to admin assets from the web. My previous pull request blocked access to these files. Sorry for the inconvenience!

### Changes proposed:

- Added a `.htaccess` file

### CODE REVIEW

**Comment by Prkns** [comment]
Can confirm that this fixes the issue 🙌🏻

**Comment by pehelwan** [comment]
Shouldn't have happened if you had followed my advice

**Comment by Radiergummi** [comment]
As we've seen with the previous patch, multiple `.htacess` files tend to cause unexpected problems. Instead of adding a third one, I'd favor reviewing the top level file.  
It should be enough to block access to `.log` files there, considering there are no other files in the `anchor/` directory relevant for security.

**Comment by tijme** [comment]
@Radiergummi I agree. I added a rule to the `htaccess.distro` file that will be written to the top level directory upon installation. I deleted the other two `.htaccess` files.

**Comment by pehelwan** [comment]
I have made a pull request to resolve it

**Comment by tijme** [comment]
@pehelwan I think #1254 still has the issue of multiple `.htaccess` files though.

**Comment by pehelwan** [comment]
@tijme Well I am trying to sort it out , though the rewrite rules solution you suggested seems to be the best fix , I m reviewing that too

**Comment by Radiergummi** [comment]
@tijme looks good to me, that's the right way to solve the issue.

**Comment by CraigChilds94** [comment]
@pehelwan @tijme Thanks for this! I'll put up another release with this fix in it!

**Pull request merged**
