### PR TITLE
Multi-Fix: Page and Posts, RSS Feed

### PR DESCRIPTION
**Pull request by TheBrenny**
@daviddarnes, As spoken about, this should fix it.

Feel free to test at: https://anchortester-mastercork889.c9.io/

Brenny :+1: :v:

### CODE REVIEW

**Comment by TheBrenny** [comment]
Latest commit fixes the RSS feed issue #881. However, there's one more bug that I would like to iron out before this gets merged.

**Comment by TheBrenny** [comment]
This PR is now ready to be merged. Hopefully I haven't missed anything.

:v:

**Comment by daviddarnes** [comment]
@TheBrenny thanks for the demo, saves me striking up a version :)

**Comment by TheBrenny** [comment]
Once all the latest PRs have been merged, I'll update that demo. :D

**Pull request closed without merging**
