### PR TITLE
Updated German translation

### PR DESCRIPTION
**Pull request by Radiergummi**
I added the missing entries (mostly page type and such), corrected spelling and grammar errors and rewrote some sentences to cleaner, more suitable German.
Maybe someone speaking German can review this before merging?

### CODE REVIEW

**Comment by daviddarnes** [comment]
This is great work @Radiergummi, but could you submit this to the Anchor Translations repo? https://github.com/anchorcms/anchor-translations

**Comment by Radiergummi** [comment]
Yes I will, but is there any reason why the german translation is still in the main repo?

**Comment by daviddarnes** [comment]
Good question. The translation in there appears to be at least a year old. They should probably be removed or supplemented with a placeholder referring to the translations repo.

**Comment by TheBrenny** [comment]
We could possibly append the google translate widget throughout the installer, and we can have it set up to pass the current language choice to the next GET request? Or we could add a link that fades between different languages that points towards the translations repo?

**Comment by daviddarnes** [comment]
@TheBrenny something like your second idea could work. I think we discussed this in another issue. I recall suggesting a set of default languages and then a link to download additional ones, that way the CMS stays lean but still provides a wide selection of languages to the user.

**Comment by TheBrenny** [comment]
I guess I'll make a quick spinner and add it into Anchor. I think I might need to use jQuery though - ruining the core idea of Anchor. We'll see what I come up with though. :stuck_out_tongue_winking_eye:

**Comment by TimohStudios** [comment]
I like the idea of automatically detecting a language, setting that as suggested (selected) in some sort of searchable dropdown with a language list, and then downloading the selected language and setting it. As far as requiring jQuery is concerned, if that's the only way that you can get this done, I suggest that you just go for it and use jQuery as a prototyping tool. Then I (or somebody else) can rewrite it into some vanilla Js.

**Comment by daviddarnes** [comment]
@TheBrenny what would you need jQuery for?

**Comment by TheBrenny** [comment]
[This](http://jsbin.com/gozafomahu/) sort of effect... It's the only way I could think of adding a spinner in - but I think we had different ideas behind the word spinner? When an installer done right comes to mind, I think of iOS, when they spin through all the different languages for the initial instruction.

**Comment by TimohStudios** [comment]
I like [something like this](http://www.lessanvaezi.com/filter-select-list-options/) a lot. I'm not familiar with the iOS install, so I don't know how that could work for us. I've yet to find a good vanilla Js implementation for this, but I'm up for writing it myself once the functionality is there.

**Comment by TheBrenny** [comment]
Timoh, there's a [jQuery plugin which does that and it's sitting in the 0.9-dev branch](https://github.com/anchorcms/anchor-cms/blob/0.9-dev/install/views/assets/js/chosen.jquery.min.js), (this link thing is cool, :stuck_out_tongue_winking_eye:). I was confused because plugins are plugins, so unless 0.9-dev has plugins, or it's a standalone, it's taking up space...

**Comment by TimohStudios** [comment]
Stuff is weird.

**Comment by TheBrenny** [comment]
But I guess because it was merged, we're allowed to use jQuery? But I also don't understand the jQuery 1 part... jQuery was rebuilt, and jQuery 2 browser requirements fit with Anchor browser requirements... And plus, everyone who uses the Google search engine has jQuery in their cache, (unless it's deleted)...

**Comment by daviddarnes** [comment]
The implementation of this is getting far too complicated. We already have a dropdown that allows us to select a language or type it out when going through the install process. We just need to add a method of installing languages that don't come as default.

Can we move this discussion to another issue please?

**Pull request closed without merging**
