### PR TITLE
Update style.css

### PR DESCRIPTION
**Pull request by felberj**
improved code field (added linebreaks)

### CODE REVIEW

**Comment by CraigChilds94** [comment]
I don't see the benefit of this at all? also you've submitted the PR to `master` whereas we'd rather you PR from the current development build's dev branch, which is currently `0.9-dev`. Please ensure you read the contributing guidelines when submitting a pull request.

**Comment by felberj** [comment]
without this the following html code 
```html
<code>
function bar(){
    return 0;
}
</code>
```
generated by
```
\```
function bar(){
    return 0;
}
\```
```
will be rendered as
```javascript
function bar(){return 0;}
```
instead of
```javascript
function bar(){
    return 0;
}
```
If you are interested in this pr, I will resubmitt it on `0.9-dev`

**Comment by TheBrenny** [comment]
@felberj, have you got a demo up and running? I would look at this on my website, but I have an external script organizing my code blocks.

**Comment by felberj** [comment]
@TheBrenny no demo but a jsfiddle:
http://jsfiddle.net/3g6oz08z/1/

**Comment by TheBrenny** [comment]
Ahh I see, but you should really follow the contribution rules...

**Comment by TimohStudios** [comment]
Doesn't Markdown already wrap
```
code
in <pre> tags?
```
(it does actually, that block was  generated by using three backticks and it's wrapped in pre tags)  
I think this change is unnecessary.

**Comment by felberj** [comment]
in `0.9 dev` when I write (without `\`)
```
\```
function hello(){
    return "world";
}
\```
```
I'm getting
```html
<p><code>function hello(){
    return "world";
}</code></p>
```
which gets rendered on one line, without the css modification

**Comment by TimohStudios** [comment]
Really? That's interesting. In that case, I think this is more of a Markdown issue than a CSS issue. This also explains why people have been having so much trouble with code highlighters. Might be time to switch to Parsedown.

**Comment by felberj** [comment]
To be clear, I'm talking about adding a post in 'example.com/admin/posts/add'

**Comment by TimohStudios** [comment]
That's what I thought. It doesn't really matter though.

**Pull request closed without merging**
