### PR TITLE
Fix for alt+s bug.

### PR DESCRIPTION
**Pull request by moje-s**
The Polish users need alt+s shortcut to create the letter 'ś'. So it
can not use both, ctrl+s and alt+s to save post.

### CODE REVIEW

**Comment by moje-s** [comment]
I am sorry for those commits instead a new pulls. 
I am testing the GitHub Desktop...

**Comment by daviddarnes** [comment]
@moje-s was that an accidental close?

**Comment by moje-s** [comment]
@daviddarnes yes, I tried to figure out how works GitHub Desktop. It have a one plus, it is looks nice ;)

**Comment by CraigChilds94** [comment]
@moje-s I've noticed that you continued to commit to the branch that you used for this PR; are those extra commits integral to this working? 

I'll look into merging this in when I get a chance as we're getting conflicts on it at the moment.

**Comment by moje-s** [comment]
The third commit (Layout fix in for Polish translation - menu) regquire the second commit (The language class in body). The rest of commits is independent from each others. 

I am sorry for this conflict, I tested a desktop applications for git.

**Comment by daviddarnes** [comment]
@moje-s can you submit these independent changes as different pull requests please?

**Comment by moje-s** [comment]
All of commits or just some of them?

**Comment by daviddarnes** [comment]
@moje-s if the commits are linked they should be in one commit. The idea is that pull requests should be one feature or one fix.

**Comment by moje-s** [comment]
I will delete my fork and create the new one, now it is too bug mess in there.

**Pull request closed without merging**
