### PR TITLE
Updated style.css and run.php | Fixed Issues #889 #893

### PR DESCRIPTION
**Pull request by giacomocerquone**
As I said here: https://github.com/anchorcms/anchor-cms/issues/889
When you try to use the "quote" (in md syntax is >) the default theme doesn't style correctly the blockquote tag. I'm on Windows 8.1, Chrome 64bit v. 44.0.2403.81.

### CODE REVIEW

**Comment by TheBrenny** [comment]
I see no issues with this one... So long as it doesn't break any other content classes...

**Comment by giacomocerquone** [comment]
This is what I see using ">" without my correction on style.css:
http://i60.tinypic.com/bdt738.png
This is what I see using ">" with my correction on style.css:
http://i59.tinypic.com/2640u1l.png

**Comment by TheBrenny** [comment]
Awesome. But it should also have a PR to 0.9-dev.

**Comment by giacomocerquone** [comment]
PR stands for?

**Comment by giacomocerquone** [comment]
Here to see the bugfix of the timezone: http://www.giacomocerquone.it/blog/anchor-install/
Here to see the bugfix of the style.css: http://www.giacomocerquone.it/blog/posts/hello-world

**Pull request closed without merging**
