### PR TITLE
Added RSS and JSON feeds

### PR DESCRIPTION
**Pull request by ftzeng**
This PR adds RSS and JSON feeds as [implemented here](http://latitudu.com/notes/anchor-cms/rss-feeds-by-specific-category) and suggested in #511.

### CODE REVIEW

**Comment by TimohStudios** [comment]
I like the idea, but I personally don't think this is something for Anchor's core. It wouldn't be the best for everyone and doesn't really work with the idea of keeping Anchor lightweight and small. I think this would work better as a plugin.

**Comment by CraigChilds94** [comment]
When I get a chance I'll go through and evaluate this. @TimohStudios might be right, but I think it's best to check in with someone else. Theres a lot of talk about what would be better as a plugin and what wouldn't and it seems that a lot of stuff would be better as the former but as they're currently not implemented it seems such a shame to just throw good ideas away.

What do you think @daviddarnes or @rwarasaurus ?

**Comment by daviddarnes** [comment]
I have to agree with @TimohStudios on this. While this is an awesome addition I think it would be better in the form of a plugin. I think we've already had a similar discussion regarding a sitemap.xml plugin, so it makes sense to do the same with this.

I could see this being quite powerful too, with the ability to choose what is in the feed and what file format to output it as. Please don't take this as a negative @ftzeng, we always appreciate contributions, but we'd rather be implemented as a plugin. That way the core stays light, plus you get to take more credit for your work :smiley:.

**Comment by ftzeng** [comment]
No problem! Can you point to a resource for making anchor plugins?

**Comment by daviddarnes** [comment]
:sob: http://anchorcms.com/docs/class-reference/plugin

If we can get plugins into a state where people can even just start making them then it'll be a good enough start. This will be the 3rd request about plugins this week!

**Comment by ftzeng** [comment]
Alright, I'll close this issue and convert this to a plugin when anchor's ready for it, looking forward to it!

**Comment by CraigChilds94** [comment]
Plugins keep cropping up these days :'( we need to get `v1.0` out @rwarasaurus 

**Note**

To anyone who creates something cool or integrates a "plugin" into there version of Anchor it'd be great if you could share it on the [forums!](http://anchorcms.com/forum)

**Pull request closed without merging**
