### PR TITLE
Autosave feature implemented

### PR DESCRIPTION
**Pull request by TheBrenny**
Closes issue #879, however, some changes may need to be made to a few things.

When autosaving a new article/page (ie. when adding a new article/page) after the first autosave, you will be redirected back to the posts/pages index page. This seems like a bug, but you can easily just go back to the article/page you were writing, turn on autosave, and continue as normal.

I edited the pages' redirect button, at the time, if any `<button class="secondary"></button>` had been pressed, it would make the page a redirector page. I noticed this while testing out the autosave feature, and decided to fix it.

There may be other bugs, however, I see none.

### CODE REVIEW

**Comment by CraigChilds94** [comment]
I think if this has a bug, it shouldn't be merged in until that has been fixed

**Comment by TheBrenny** [comment]
It depends whether we force the user to continue editing, or to force them back once they are done adding a(n) article/post. Maybe an added variable is sent upon submitting to dertimine which save feature submitted.

Perhaps we could also add the auto save feature into the site extension list, and have a boolean in the DB to say yes or no to auto save upon opening.

I'll think about these after the pagination issue! :smile:

**Comment by CraigChilds94** [comment]
@TheBrenny how come you deleted this? I was going to merge them all in man!

**Comment by TheBrenny** [comment]
Oh crap! I knew it was going to be a bad idea to close all those branches. I thought it wouldn't effect anything else. I should be able to pluck the changes out and start a new PR. Its a shame GH doesn't let you open two branches if they're forked from the same original branch. :(

**Pull request closed without merging**
