### PR TITLE
Added Ubuntu 14.10

### PR DESCRIPTION
**Pull request by tk421**
Added the server configuration template for Ubuntu 14.10

### CODE REVIEW

**Comment by TimohStudios** [comment]
Neat! It does look like you changed the formatting from the current readme. Could you take a look at that?

**Comment by tk421** [comment]
@TimohStudios I just added Ubuntu 14.10. What do you mean that I change the formatting ? Could you be more specific ?

**Comment by TimohStudios** [comment]
I invite you to [take a look at the current readme](https://github.com/anchorcms/anchor-cms/blob/master/readme.md). It mentios that you supplied it. What I think went wrong is that your fork is outdated.

**Comment by tk421** [comment]
@TimohStudios  understood now. You are right and my fork is outdated.

**Comment by tk421** [comment]
Created a new pull request #817

**Pull request closed without merging**
