### PR TITLE
Show value of the posts_per_page slider

### PR DESCRIPTION
**Pull request by cybrox**
Always show the value of the posts_per_page slider in the admin interface.
Tested with a fresh installation.

### CODE REVIEW

**Comment by TimohStudios** [comment]
:+1:

**Comment by CraigChilds94** [comment]
I'm pretty sure this was already fixed at some point but I can't honestly remember. When I go through PR's I'll take a look at this one :) I always thought it was a bit unusual that no one had done this sooner :) Thanks for your contirbution, and sorry for such a late reply!

**Comment by cybrox** [comment]
The only related PR I found was [this one](https://github.com/anchorcms/anchor-cms/pull/775), which was apparently not working and merged against the wrong branch. - And didn't seem to get any update from then on.
I don't know if this has been fixed by another commit in between, I haven't really played around with direct master forks from anchor since development seemed pretty dead lately ( :cry: )

**Comment by CraigChilds94** [comment]
Thanks for this, merged now. It's been bugging me for a while that I couldn't see the value but I didn't do anything about it :see_no_evil:

**Pull request merged**
