### PR TITLE
Improve Not Configured Message

### PR DESCRIPTION
**Pull request by matthew1471**
Attempt number 3 to commit to Anchor (#803, #1075)

- Better error message for end-users.
- Returns correct HTTP status code to prevent search ranking issues.
- Returns valid web-page to assist robots.

### CODE REVIEW

**Comment by rwarasaurus** [comment]
Do we really need all those echo calls?

**Comment by matthew1471** [comment]
Definitely, but I went for code readability over performance. I also went for standards compliance rather than just a straight bomb out with an error rather than a well formed web-page.

The text could be shortened to be less user-friendly.. but I figured users browsing the site might appreciate a more informative error.

Happy to learn how I can further improve it.

**Comment by Gerrit0** [comment]
Personally, I would change it to something like this:

```PHP
<?php
if (!file_exists(PATH . 'vendor')) {
    // Let web crawlers know this isn't a proper anchor-cms page (prevents search ranking drop).
    header('HTTP/1.1 503 Service Temporarily Unavailable');
?>
... Your error page...
<?php
    exit();
}
```

**Comment by matthew1471** [comment]
It's a bit contentious and now comes down to coding style.

>Text outside of <?php ?is compiled to echo operations. So there's no basic difference between the two methods.
https://bytes.com/topic/php/answers/561496-performance-lots-echos-v-jumping-out-php

Though admittedly it would probably be a few functions less echos.

Also see http://programmers.stackexchange.com/questions/180501/which-is-better-to-include-html-inside-php-code-or-outside-it#comment515044_180501

**Comment by CraigChilds94** [comment]
The preferred option here would be to load in a stored template as it's more readable and easier to maintain. Thanks for the suggestion though :)

**Pull request closed without merging**
