### PR TITLE
Store both Markdown and rendered HTML. Closes #744.

### LINKED ISSUE #744: Feature: Store both Markdown and rendered HTML when saving pages and posts
I was looking through the Markdown class yesterday, wondering if [Parsedown](https://github.com/erusev/parsedown) could replace it, and I noticed that the database only saves *the Markdown content* for posts and pages.

I was wondering why is this? Wouldn't it be more efficient to save the markdown *and the HTML* into the database instead of having a "render content as HTML" function for the frontend? The markdown for a page is probably modified much less than the number of times the HTML is viewed by site visitors.

The `article_html` function could be reduced to the same weight as reading any other static property of a page or post.

I can tackle this feature if there is an actual need for it. I realize adding Parsedown, would be a different conversation.

### PR DESCRIPTION
**Pull request by james2doyle**
Ok so here is the mighty solution to #744.

I normalized 2 of the database fields. Posts and pages now both have a `markdown` and `html` column. Instead of a mix of `content` and `html`, which was a little confusing.

I **kept the language files the same**, which means they still have the word `content` in their key names. I don't see this as all bad, since we don't need to change any language files at all if the key remains the same. It's up to the team to decide if it should change.

Everyone should see a nice bump in rendering time!

### CODE REVIEW

**Comment by TimohStudios** [comment]
I guess this can be merged now, right?

**Comment by james2doyle** [comment]
I believe so, the only thing is *the data for the install is now incorrect because the first post and page have their content in the wrong fields...*

**Comment by CraigChilds94** [comment]
When I get around to looking at PR's I can see about merging this in, thanks for all of your hard work!

**Comment by TimohStudios** [comment]
Yes! Amazing that this is finally implemented. I think this is a great change. Thanks @james2doyle and @CraigChilds94!

**Comment by james2doyle** [comment]
Awesome! Thanks

**Pull request merged**
