### PR TITLE
Fix for Menu_Render() function not correctly outputting complex nested p...

### PR DESCRIPTION
**Pull request by csengineer13**
...arent/child structures

This is a dupe of the merge I put against Master. A little new to Pull Requests and your flow, so please let me know if I need to change anything.

Best,
DB

### CODE REVIEW

**Comment by CraigChilds94** [comment]
Thanks, will check it out soon!

**Comment by csengineer13** [comment]
I see that this was closed, but I don't think it was merged in. Just curious, was something wrong?

**Comment by CraigChilds94** [comment]
Oh no, sorry I changed the name of the branch but silly me forgot that it would break PR's and now theres no going back :( Is it okay if you could please resubmit to `0.10-dev`?

**Comment by csengineer13** [comment]
So...? (:

**Comment by TheBrenny** [comment]
Oh my! I didn't see that this had already been made into a PR. Although I admit, I haven't managed the *complex* part of the family tree, I have done something that fixes it. Look at #887.

**Pull request merged**
