### PR TITLE
Fix syntax error that triggers a php error on installation.

### PR DESCRIPTION
**Pull request by dwks**

### CODE REVIEW

**Comment by tlongren** [comment]
If someone from the group wants to give me write access to this repo, I can merge this right away. I've tested it multiple times without any issues.

**Comment by Lex720** [comment]
I think that it has been a while since no one from the admins paid attention to this repo, do you know if they still are accepting pull request? or if they left this project unattended?

**Comment by daviddarnes** [comment]
@Lex720 Very much paying attention.

@dwks We'd very much appreciate an explanation of what this PR fixes?

**Comment by dwks** [comment]
It's pretty self-explanatory. There was a syntax error in the PHP, a "?" operator without the matching ":". The original author typed an "=" by accident. Anyone trying to do a clean install of anchorcms will run into a fatal PHP syntax error because of this. It's really pretty serious since it will affect all new users who perform an installation as suggested by the docs, but fortunately it's a very easy fix. I tested the fix and it works (and it sounds as if @tlongren did as well).

**Comment by daviddarnes** [comment]
@dwks thanks for the info. Though I would've thought this bug would've come up earlier in testing, strange.

**Comment by dwks** [comment]
Yeah, the bug has been present for 2.5 months since Aug 27th -- https://github.com/anchorcms/anchor-cms/commit/c3e520cf166461ee568d24df7abae0fdfa521ef7
I guess testing of clean installs isn't being done very often. Or perhaps there is a way to install without triggering this bug, but I can't really see how. Any use of install/run.php should error out.

**Comment by tlongren** [comment]
Just to confirm what @dwks has stated, this only happens when doing a fresh install. I've done a few fresh installs lately (within the last month) from master and have run into this every time.

**Pull request merged**
