### PR TITLE
Fix gmt error from installing

### PR DESCRIPTION
**Pull request by JREAM**

### CODE REVIEW

**Comment by NathanLawrence** [comment]
It looks like pull request 921 also attempts to address this. I'm not well enough versed in this particular issue to understand if the placement of the parenthesis actually affects the outcome, but I *really* look forward to one of these fixes getting pulled in, especially since one of the recommended installs involves cloning this (currently unusable) repo.

**Comment by JREAM** [comment]
Sorry I did not see that PR. I haven't gone through all of it, but this is definately something that must be addressed! :)

**Comment by TheBrenny** [comment]
The `contributing.md` file has a set of rules that should be followed when making PRs... I'm not trying to ream you, but the file states to look if a PR or Issue has already been created. Now the team needs to go through which PR to pull, which vastly slows down the quality assurance step - although it *may* (or may not) provide beneficial outcomes.

**Comment by JREAM** [comment]
Yeah I see i didnt even branched, I got github happy, since the issue exists let me kill it. Looks like we had different solutions lol but its close: https://github.com/anchorcms/anchor-cms/pull/921

**Pull request closed without merging**
