### PR TITLE
Spaces to Tabs in all files

### PR DESCRIPTION
**Pull request by davidapple**
### Changes proposed:

- I have changed all spaces to tabs in all files for consistency.

### CODE REVIEW

**Comment by daviddarnes** [comment]
I appreciate that this brings a lot of consistency, but some of the indentation has been affected, for example https://github.com/anchorcms/anchor-cms/blob/54c88e64a775283649ea9884c9bdfa8f3f13c4d0/test/teardown.js

Maybe we should add an editorconfig file so our code editors can pick up on the same coding style?

**Comment by Radiergummi** [comment]
@daviddarnes +1 for the editorconfig file, that'd be for the best. And while we're at it: tabs vs. spaces!  
Vote 🎉 for spaces, :heart: for tabs on this comment!

**Comment by protomorph** [comment]
there already is an editorconfig file https://github.com/anchorcms/anchor-cms/blob/master/.editorconfig and it's already set to spaces https://github.com/anchorcms/anchor-cms/blob/master/.editorconfig#L8

**Comment by CraigChilds94** [comment]
@davidapple yes the project needs to be consistent but spaces is the convention we're following for PHP files. 

https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-2-coding-style-guide.md

**Pull request closed without merging**
