### PR TITLE
Radiergummi migrate to scss

### PR DESCRIPTION
**Pull request by Radiergummi**
### Feature for #1210 
After a lot of discussion on #1210, I decided to rewrite the current admin CSS cleanly in SCSS. This will allow us to modify the CSS way more easily, if needed. There are added benefits, including:
- optimization and minification of the CSS output, resulting in smaller files
- automatic compatibility features, including vendor prefixes, that don't have to be written by hand anymore
- Code style linting included

The SCSS is split up roughly by components, where applicable. This initial PR does not contain any changes of the current style (meaning: The generated CSS file results in Anchor looking exactly the way it did before), though I plan on making the interface responsive and use SVG sprites, among other ideas.

Further on, I created a gulp file to ease the process of building assets, which does also include tasks to optimize images and JavaScript. The JavaScript related work is not ready yet, since I'd like to take the opportunity and remove Zepto aswell - we can do easily with plain JS. I'll reference that in further commits.

This PR will need a bit of discussion, since I'm sure not everyone will agree with my style of writing SCSS or the rest of this text at all 😄 We'll see. 

### Changes proposed:
- Added npm with package.json
- Added gulp with gulpfile.js
- Added SCSS linting with scss-lint.yml
- Rewrote and split up CSS into new SCSS structure

bildschirmfoto 2017-07-25 um 08 50 47

### CODE REVIEW

**Comment by daviddarnes** [comment]
Nice job @Radiergummi! A great first step. Also pleased we're able to drop Zepto. I was hoping to do this myself but I really don't have the time right now, so pleased others are able to take this on. If possible, I'd like to contribute tweaks and UI changes to improve structure and accessibility.

**Comment by TheBrenny** [comment]
@daviddarnes Isn't Zepto used as a hugely minified jQuery, keeping only the important bits, like AJAX and such?

**Comment by daviddarnes** [comment]
@TheBrenny you're right, but do we use ajax? I would've thought most of the interactions and behaviours we can do with modern es6?

**Comment by Radiergummi** [comment]
Looking at the code, we should certainly be able to use plain JS for all current features.. Maybe we'd even manage to implement more AJAX features :)

**Comment by CraigChilds94** [comment]
Nice work dude!

**Pull request merged**
