### PR TITLE
Uncaught exception when Anchor is running on a machine without internet connectivity

### PR DESCRIPTION
**Pull request by joeinnes**
Fixes issue #794: uncaught exception when Anchor is running on a machine without internet connectivity.

After installing Anchor, the website loads, and the admin login interface is fine, but when I try to log into the admin panel, there's an uncaught exception error. I believe this to be due to a lack of error handling if there is no network connectivity.

This normally would not be an issue on a production box, but a dev box running in a VM or as a standalone may not have an internet connection.

Uncaught Exception

file_get_contents(): php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution

Origin

anchor/libraries/update.php on line 55

Trace

#0 [internal function]: System\Error::native(2, 'file_get_conten...', '/var/www/public...', 55, Array)
#1 /var/www/public/anchor/libraries/update.php(55): file_get_contents('http://anchorcm...', false, Resource id #2)
#2 /var/www/public/anchor/libraries/update.php(18): Update::touch()
#3 /var/www/public/anchor/libraries/update.php(8): Update::setup()
#4 /var/www/public/anchor/routes/admin.php(54): Update::version()
#5 [internal function]: {closure}()
#6 /var/www/public/system/route.php(152): call_user_func_array(Object(Closure), Array)
#7 /var/www/public/system/router.php(152): System\Route->run()
#8 /var/www/public/system/start.php(36): System\Router->dispatch()
#9 /var/www/public/index.php(33): require('/var/www/public...')
#10 {main}

### CODE REVIEW

**Comment by TimohStudios** [comment]
Awesome! Would you mind rebasing your PR to 0.9 dev?

**Comment by joeinnes** [comment]
Sure, will do.

**Comment by joeinnes** [comment]
You want me to submit a new PR too? Just realised this is targetted at master.

**Comment by CraigChilds94** [comment]
Yes please, sorry we're all super busy at the moment but as soon as we get the time we'll take a look at all of these PR's

**Comment by DoyleDarren** [comment]
Hi, I notice some of the documentation is missing from the Anchor website. Are you looking for people to contribute to these? I can write up the missing pages in Markdown.

**Comment by CraigChilds94** [comment]
@DoyleDarren Yeah unfortunately we haven't been ablte to keep up with both; these things are time consuming but you're welcome to help. There is a repo for the site though I can't remember whether it's public or not, you could always PR if it is.

**Comment by joeinnes** [comment]
Rebased and submitted new PR.

**Comment by CraigChilds94** [comment]
Thanks :)

**Pull request closed without merging**
