### PR TITLE
Added PostgreSQL support

### PR DESCRIPTION
**Pull request by corpsee**
Added PostgreSQL support

### CODE REVIEW

**Comment by CraigChilds94** [comment]
Oh this is interesting. I've never used it myself before so I'll have to get it setup! Only issue is the `/system` stuff isn't really part of Anchor. I think @rwarasaurus  has this setup in a separate repo, maybe consult him about this?

**Comment by corpsee** [comment]
Let's ask him) I can help with PostgreSQL integration if it is needed. I use it.

**Comment by rwarasaurus** [comment]
Have you checked all the queries? also can you send this pull to the dev branch please :)

**Comment by corpsee** [comment]
To the 0.9-dev branch?

**Comment by TimohStudios** [comment]
Yesss please

**Comment by corpsee** [comment]
The pull request can be closed.
I have already reworked PostgreSQL/SQLite DB support in another branch (inherited from 0.9-dev). And I will make it in another pull request later. 
Installation already works and the migrations remain to be done.

**Comment by magne4000** [comment]
Any news on Postgresql integration ?

**Comment by corpsee** [comment]
This request is stalled at some point.

The main problem with backward compatibility. I see two solutions for integrate Postgres and both are bad for backward compatibility:
* Support 2 separate sets of migrations for different databases (MySQL and Postgres)
* Change the DB scheme to be compatible with both DB

I have almost finished functional with Postgres, but I do not know how integrate it in the main project.

**Pull request closed without merging**
