### PR TITLE
Added LICENSE file and improved composer.json

### PR DESCRIPTION
**Pull request by corpsee**
Added LICENSE file and improved composer.json

### CODE REVIEW

**Comment by CraigChilds94** [comment]
Thanks for putting effort in to help us out with this :D 

@idiot, @rwarasaurus, @daviddarnes is this correct?

**Comment by rwarasaurus** [comment]
Yep! +1:

**Comment by corpsee** [comment]
@CraigChilds94, @rwarasaurus Tell me please, into what branch should I make pull prequests in the future? And what is master branch for if there are 0.9-dev and 1.0-dev?

**Comment by CraigChilds94** [comment]
`master` is a release branch so only versions which we would consider stable will exist in that branch, essentially it's where we tag from.

As of the next release we'll be following a better gitflow which optimises management of projects like this. Along with that an extensive document will be included detailing how things will work and what contributors must follow.

For now, we're only accepting PR's on `0.9-dev` (Unless it's change to REAME, Contibuting.md etc which are version independent)

**Pull request merged**
