### PR TITLE
Update post date if published for the first time

### LINKED ISSUE #635: Published date as the post's date?
Should the post's date be the date it was published rather than created?

For example, I started writing a post last month and only recently got around to finishing and publishing it. The post uses its creation date so the newly published post has become buried beneath posts which have been created afterwards.

### PR DESCRIPTION
**Pull request by ryanstubbs**
Sorry that I've had to create and close a couple of pull requests, I'm still learning.

Anyway, this has fixed #635 where the post date doesn't update automatically. It only updates when it has previously been a draft and is now published - presumably for the first time.

### CODE REVIEW

**Comment by TimohStudios** [comment]
This is something that really needs to be addressed. @CraigChilds94 What are your plans on this?

**Comment by lifehome** [comment]
Agree to this, but could we allow users to choose whether publishing the date by creating the draft, or the moment they switch to "published"? (as they could switch the "status")

**Comment by daviddarnes** [comment]
Best solution for publishing and setting post dates would be to set the date when the publish button is hit, but also provide a date picker for posts. Thought this might be a bit too much work for the current public version of Anchor. Maybe have the above feature added and then have a date picker in v1.0. Thoughts?

**Comment by CraigChilds94** [comment]
It is going to require some modification to the way that system is working. It should definitely be included in `v1.0` though :)

**Comment by TimohStudios** [comment]
This one into master too? Did this happen on accident maybe?

**Comment by TimohStudios** [comment]
Ok, so I just noticed it looks like you merged master into the dev branch too, which calms me down a little bit, although I still think this is wrong.

**Comment by CraigChilds94** [comment]
@TimohStudios yeah I probably shouldn't have done it but I saw this one as more of a bugfix which means it doesn't matter too much.  I'll be merging `0.9-dev` into master soon anyway

**Comment by Mullazman** [comment]
Sweet as. Any idea when the next major release might be? I've been keenly interested for a long while now haha

**Pull request merged**
