### PR TITLE
improved article pagination

### PR DESCRIPTION
**Pull request by TheBrenny**
Fixes feature/bug #863 and moved here because of a request in #864.

### CODE REVIEW

**Comment by daviddarnes** [comment]
@TheBrenny I've closed your other pull request, hope that's ok. Thanks for your contribution efforts! :star:

**Comment by TheBrenny** [comment]
It's all good. I saw somewhere back ages ago, that this cms could be coming to an end, and there's so much potential here which I rely on. I would hate for this cms to end.

**Comment by daviddarnes** [comment]
@TheBrenny coming to and end? Where did you read that? I might not be the best contributor, but I wouldn't let this plucky CMS fail without a good fight! I would hate for it to end too, and I know @CraigChilds94, @rwarasaurus and @idiot feel the same.

**Comment by TheBrenny** [comment]
I saw it far far long ago, and I could have read those words out of context. But I'm supporting this cms all the way. I use it for my website, and I'm constantly adjusting the code of anchor, for my personal needs, so I'm trying to push all my changes into clean usable code, so I can make some PRs for here. :P

**Comment by daviddarnes** [comment]
@TheBrenny :heart:

**Pull request merged**
