### PR TITLE
Improve panel.php WIP

### PR DESCRIPTION
**Pull request by naltamur**
Hello I am a student, I love this CMS and for this I want to contribute. I know HTML and CSS. 

Feature: Add Credit on panel.php
### Changes proposed:

- Add screen

Warning: This is a Work In progress

### CODE REVIEW

**Comment by naltamur** [comment]
Can anyone send me a list of contribuitors?
I Can include it on panel.php as like a about page of AnchorCMS

**Comment by naltamur** [comment]
Preview
adminpanel

**Comment by ramon-villain** [comment]
I don't get the point of this.

**Comment by daviddarnes** [comment]
We appreciate the sentiment on this contribution @naltamur, but it's not what the admin panel was designed for. Sorry

**Comment by naltamur** [comment]
Okay no problem because I love this CMS ;) Great work :)

**Pull request closed without merging**
