### PR TITLE
Add FontAwesome Icon WIP

### PR DESCRIPTION
**Pull request by naltamur**
Hello, I want contribute to Anchor because it's a great CMS
### Changes proposed:

- Add FontAwesome Icon (because I think it's better than now)

## Poll
 What Can I Use for icons?
Please select a icon from http://fontawesome.io/icons/ : I can add it here :)

PS: It's a work in progress

### Preview 
preview

### CODE REVIEW

**Comment by daviddarnes** [comment]
What is the purpose of adding icons? Does it improve useability? The Anchor icon does not match the official Anchor logo

**Comment by naltamur** [comment]
@daviddarnes Purpose is to make better Anchor. I put Anchor Icon for example because I didn t know icons.

**Comment by TheBrenny** [comment]
But increasing the size of Anchor just for glyphs that only a few users
might need?

**Comment by naltamur** [comment]
@TheBrenny now icons are 3x..

**Comment by joshvickerson** [comment]
I too question the value of adding the icons. "to make Anchor better," but in what way is this better? Maybe aesthetically, but that's highly subjective.

I also feel that icon fonts have a lot of faults. Perhaps FontAwesome has addressed them, but they can be an accessibility nightmare, as outlined in [this blog post](http://blog.cloudfour.com/seriously-dont-use-icon-fonts/).

**Comment by CraigChilds94** [comment]
I don't think this is necessary, if someone were to want to customise the icons for their personal Anchor installation it is down to them :) Thanks for contributing though, and i'm glad you like Anchor.

**Comment by naltamur** [comment]
No problem :)

**Pull request closed without merging**
