### PR TITLE
Pre-Fix Drag'n'Drop #1048

### PR DESCRIPTION
**Pull request by ramon-villain**
### Fixfor #1048 

Fixed the dragleave issue. I changed some css classes, to get it working.

fixed

### CODE REVIEW

**Comment by daviddarnes** [comment]
Wonderful, thank you @ramon-villain. But does this need to be PR'd against another branch @CraigChilds94?

**Comment by ramon-villain** [comment]
Do you mean, PR'd against the pre-1.0 branch?

**Comment by daviddarnes** [comment]
@ramon-villain I do yes sorry, I just checked the contributing file and it says to use the `pre-1.0-develop` branch.

**Comment by frozenpandaman** [comment]
Why does this PR and #1053 have the same title/description and gif? They're different changes from what I can tell…

**Comment by ramon-villain** [comment]
@frozenpandaman I did the first PR to master instead of pre-1.0… this should be closed.

**Pull request closed without merging**
