### PR TITLE
add missing german translation for edit menu

### PR DESCRIPTION
**Pull request by beli3ver**
add missing german translation for edit menu

### CODE REVIEW

**Comment by kukac7** [comment]
@beli3ver https://github.com/anchorcms/anchor-translations

**Comment by beli3ver** [comment]
Sorry, my mistake

**Comment by kukac7** [comment]
@beli3ver and? It is still in the repo.

**Comment by beli3ver** [comment]
I also do it on the anchor-translation, but there a more then 49 pull requests.
Does anybody work there?

**Comment by kukac7** [comment]
@beli3ver sorry, i don't know. :disappointed:

**Comment by daviddarnes** [comment]
@beli3ver I'm not sure what you mean by "work there"? Anchor is not a company, it's an open source project. We will hopefully get around to the pull request when we have some free time.

**Comment by beli3ver** [comment]
Maybe I could help you there. I could check it for you and merged the stuff

**Comment by daviddarnes** [comment]
@beli3ver which pull request are you referring to?

**Comment by beli3ver** [comment]
?

**Comment by daviddarnes** [comment]
@beli3ver are you referring to this? https://github.com/anchorcms/anchor-translations/pull/87

**Comment by beli3ver** [comment]
yes

**Comment by daviddarnes** [comment]
@beli3ver we will assess the code from there.

**Pull request closed without merging**
