### PR TITLE
Several Fixes: timezone-ds-bug in install, rewind categories, escape htmlentities in Extend::html()

### PR DESCRIPTION
**Pull request by aravindanve**
changed `$gmt = ($ds == 1 ? $gmt = $gmt-1 );` to `$gmt = ($ds == 1 ? $gmt-1 : $gmt);` in install/run.php:48

### CODE REVIEW

**Comment by fbrinker** [comment]
I am not able to merge a pr, but you should seperate commits and prs a little bit. The timezone fix is a bug they could merge faster than the other stuff without testing it in detail

**Comment by aravindanve** [comment]
Sorry. I have separated the commits and made pull requests.

**Comment by fbrinker** [comment]
Awesome, good work :)

**Comment by daviddarnes** [comment]
Yes! Thanks @aravindanve, appreciate PRs being broken down for better tracking :+1:

**Pull request closed without merging**
